Hw lesson14 param test
oleksandr-bondarenko-aqa/aqa-js-main pull request #4
Opened 2022-10-03 18:18 UTC by oleksandr-bondarenko-aqa

2022-10-05 08:09 UTC, SanitarskyiDmytro requested changes

2022-10-05 08:09 UTC, SanitarskyiDmytro commented on cypress/e2e/hw-lesson-14.cy.js
> +    it(('Check top-left success'), () => {
Все працює чудово, але головна ідея параметризованих тестів в тому щоб скоротити кількість коду. Подумайте, як переробити ваш тест так, щоб він запускався через .forEach()

2022-10-06 06:31 UTC, oleksandr-bondarenko-aqa commented on cypress/e2e/hw-lesson-14.cy.js
> +    it(('Check top-left success'), () => {
optimized code, used forEach()

2022-10-09 13:34 UTC, SanitarskyiDmytro approved these changes

2022-10-11 16:24 UTC, merged